# Generated by Django 4.1.4 on 2022-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ispublic',
            field=models.CharField(max_length=1),
        ),
    ]
